defmodule Wagger.Generator.Coraza do
  @moduledoc """
  Coraza/ModSecurity WAF config generator implementing the `Wagger.Generator` behaviour.

  Produces a standalone SecRule `.conf` file with:
  - `SecRuleEngine` and `SecDefaultAction` engine directives
  - Per-route `SecRule` entries with chained method enforcement
  - Rate-limit annotations as comments (not natively supported)
  - A catch-all deny rule for undeclared paths
  """

  @behaviour Wagger.Generator

  alias Wagger.Generator.PathHelper

  @default_start_rule_id 100_001
  @catch_all_offset 90_000

  @impl true
  def yang_module do
    Path.join(:code.priv_dir(:wagger), "../yang/wagger-coraza.yang")
    |> File.read!()
  end

  @impl true
  def map_routes(routes, config) do
    start_id = parse_int(config, "start_rule_id", @default_start_rule_id)
    rule_engine = config[:rule_engine] || config["rule_engine"] || "On"
    config_name = config[:prefix] || config["prefix"] || "coraza"

    rules =
      routes
      |> Enum.with_index()
      |> Enum.map(fn {route, idx} ->
        r = normalize(route)
        pattern = PathHelper.to_regex(r)

        base = %{
          "id" => start_id + idx,
          "path-pattern" => pattern,
          "methods" => r.methods
        }

        base =
          if r.description do
            Map.put(base, "description", r.description)
          else
            base
          end

        if r.rate_limit do
          Map.put(base, "rate-limit-comment", "#{r.rate_limit} req/min (enforce at proxy layer)")
        else
          base
        end
      end)

    %{
      "coraza-config" => %{
        "config-name" => config_name,
        "generated-at" => iso8601_now(),
        "rule-engine" => rule_engine,
        "default-action-phase" => 1,
        "default-action-status" => 403,
        "start-rule-id" => start_id,
        "rules" => rules,
        "catch-all-rule-id" => start_id + @catch_all_offset
      }
    }
  end

  @impl true
  def serialize(instance, _schema) do
    cfg = instance["coraza-config"]
    config_name = cfg["config-name"]
    generated_at = cfg["generated-at"]
    rule_engine = cfg["rule-engine"]
    phase = cfg["default-action-phase"]
    status = cfg["default-action-status"]
    rules = cfg["rules"]
    catch_all_id = cfg["catch-all-rule-id"]

    header = """
    # Generated by Wagger for app: #{config_name}
    # Timestamp: #{generated_at}

    SecRuleEngine #{rule_engine}
    SecRequestBodyAccess On
    SecDefaultAction "phase:#{phase},log,auditlog,deny,status:#{status}"
    """

    rule_blocks =
      Enum.map_join(rules, "\n", fn rule ->
        render_rule(rule, status)
      end)

    catch_all = """
    # Deny all undeclared paths
    SecRule REQUEST_URI "@rx .*" "id:#{catch_all_id},phase:#{phase},deny,status:#{status},msg:'No matching route'"
    """

    (header <> "\n" <> rule_blocks <> "\n" <> catch_all)
    |> String.trim_trailing()
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  defp normalize(route) do
    %{
      path: route[:path] || route["path"],
      path_type: route[:path_type] || route["path_type"],
      methods: route[:methods] || route["methods"],
      rate_limit: route[:rate_limit] || route["rate_limit"],
      description: route[:description] || route["description"]
    }
  end

  defp render_rule(rule, _status) do
    id = rule["id"]
    pattern = rule["path-pattern"]
    methods = rule["methods"]
    description = Map.get(rule, "description")
    rate_comment = Map.get(rule, "rate-limit-comment")

    methods_str = Enum.join(methods, " ")

    comment =
      if description do
        "# #{methods_str} #{original_path_from_pattern(pattern)} — #{description}"
      else
        "# #{methods_str} #{original_path_from_pattern(pattern)}"
      end

    rate_line =
      if rate_comment do
        "\n# Rate limit: #{rate_comment}"
      else
        ""
      end

    """
    #{comment}#{rate_line}
    SecRule REQUEST_URI "@rx #{pattern}" "id:#{id},phase:1,chain,allow"
      SecRule REQUEST_METHOD "@pm #{methods_str}" "t:none"
    """
  end

  defp original_path_from_pattern(pattern) do
    pattern
    |> String.replace_prefix("^", "")
    |> String.replace_suffix("$", "")
    |> String.replace_suffix(".*", "/")
  end

  defp iso8601_now do
    DateTime.utc_now()
    |> DateTime.truncate(:second)
    |> DateTime.to_iso8601()
  end

  defp parse_int(config, key, default) do
    val = config[String.to_atom(key)] || config[key]

    case val do
      nil -> default
      v when is_integer(v) -> v
      v when is_binary(v) -> String.to_integer(v)
    end
  end
end
